### ISSUE TITLE
Source code required for Interposer 1.3.3.0

### ISSUE THREAD

**Issue by Kaldaien** [NVIDIAGameWorks/Streamline#10]
### Please release the code

![image](https://user-images.githubusercontent.com/13346629/220745926-8332b413-89ad-49ce-a606-0f317f262269.png)

Special K requires recompiling the interposer DLL so that it does not load and hook `dxgi.dll` from System32.

There are numerous shipping games now that require 1.2 and now even 1.3 versions of the interposer in order for stuff like DLSS Frame Generation to work.

Our users are understandably upset that they have to either give up our software or lose features on their very expensive 40 series GPUs.

We're kind of upset that release builds of the Streamline Interposer do not read a config file, there has got to be a long-term solution to make Streamline stop loading and hooking the system DLL and then exploding spectacularly :) Re-compiling the interposer DLL for every release is our only solution right now and we cannot do this until the source code is released.

**Comment by jake-nv** [comment]
Thanks for reporting this.  This issue is now over a year old, hopefully you resolved the it some other way.

In any case, there's currently no plans to release source for 1.x release now that 2.x has been out for a year.
