### ISSUE TITLE
Linux support planned?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Streamline#11]
Hi,

Streamline 2.0 has been released and seems it brings support for Vulkan for the first time..
At least 1.1 documentation mentioned dx only support..
But Stremline 2.0 even with VK support, still seems Windows only, which is sad as DLSS supports Linux also..
should be possible to attemp a Linux port for people outside Nv, as almost all library has source code available.. except the new DLSS-G plugin, which is provided in binary form only, if understood correctly..
So hope NV interested in providing Linux support (with DLSS-G support too..)
Hope once/if people add Streamline support for FSR2.x (& 3.0), they add also support for Linux ( as FSR 2.x supports Vulkan so Linux friendly)..
To end, say no need for shipping a Linux product, but would be nice to be able to integrate DLSS-G on Linux via Streamline on some of my toy projects..

Edit: useful, for potential Linux support, for new NV Path Tracing SDK, which plans to integrate Steamline 2.0 for DLSS-G frame generation support..

Thanks..

**Comment by oscarbg** [comment]
hoping for GDC'24 news on Streamline linux support!

**Comment by jake-nv** [comment]
Nothing was announced at GTC or GDC. 

In general, we won’t comment on future plans (or lack thereof).

**Comment by oscarbg** [comment]
Ok, but please don't close the issue.. question is not answered and also
can change title to "Request: Linux Support" so still not solved also..
