### ISSUE TITLE
About AMD FSR2 and Intel XeSS integrations..

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Streamline#12]
Hi,
any progress so far?
last year (https://www.tomshardware.com/news/nvidia-streamline-aims-to-simplify-developer-support-for-upscaling-algorithms), some sites cited support from other IHVs like Intel interest on integrating XeSS support into StreamLine..
Maybe there is a branch somewhere on github by Intel devs with XeSS StreamLine support?

**Comment by toinouH** [comment]
XeSS is even mentioned on the nvidia page presenting Streamline.

**Comment by oscarbg** [comment]
Asked also to xess developers if theyare willing to help: https://github.com/intel/xess/issues/12

**Comment by oscarbg** [comment]
Asked also to amd devs if they are willing to help: https://github.com/GPUOpen-Effects/FidelityFX-FSR2/issues/106

**Comment by dyanikoglu** [comment]
Looking at current behavior of AMD towards DLSS (not allowing DLSS on partnered games), this sounds impossible to happen in near time.

**Comment by jake-nv** [comment]
We generally won’t comment on future plans. 

But you could definitely implement the plugins yourself: https://github.com/NVIDIAGameWorks/Streamline/blob/main/source/plugins/sl.template/templateEntry.cpp

**Comment by skarab** [comment]
Hello @oscarbg , any news on this ? I'm trying to find an implementation/plugin of FSR 2/3 but can't find anything, no fsrEntry.cpp anywhere.
