### ISSUE TITLE
Support Visual Studio 2022

### ISSUE THREAD

**Issue by Dev-Taehui** [NVIDIAGameWorks/Streamline#13]
Currently, Streamline v2.0 supports only VS2017/2019
Please support VS2022

**Comment by oscarbg** [comment]
+1

**Comment by BattleAxeVR** [comment]
+2

It's Q3 2023, VS 2022 should be the default now.

**Comment by Dev-Taehui** [comment]
It seems to support VS 2022. I will close it.
