### ISSUE TITLE
DLSS-G - Missing production dll?

### ISSUE THREAD

**Issue by Renerte** [NVIDIAGameWorks/Streamline#18]
Both `nvngx_dlssg.dll` in `bin/x64` and `bin/x64/development` are non-production builds, where do we obtain the library for release?

![image](https://github.com/NVIDIAGameWorks/Streamline/assets/1123307/3d86456d-aca1-43c3-a0da-eaa7b25ab46a)

For reference, the same version but production build found in the files of Cyberpunk 2077:

![image](https://github.com/NVIDIAGameWorks/Streamline/assets/1123307/5aa6f1ec-7000-4151-9600-e13af0861f60)

**Comment by jake-nv** [comment]
`bin/x64/` mistakingly contained non-production binaries.  This was fixed in v2.2+
