### ISSUE TITLE
Any plan for DLSS-G plugin open source?

### ISSUE THREAD

**Issue by zz817** [NVIDIAGameWorks/Streamline#21]

**Comment by zz817** [comment]
I just want to support dx11 for dlss-fg

**Comment by vityafx** [comment]
Perhaps, if not feasible with open source, then just an interface to use it and the library built for Linux?

**Comment by jake-nv** [comment]
There is currently no plan to open-source DLSS-FG plugin.

**Comment by iddm** [comment]
Are there any plans to at least have a Linux native-build library?

**Comment by jake-nv** [comment]
When I said "currently no plan", I mean not scheduled for the next release or two.
In general, we can't comment on "future plans" (or lack thereof).
