### ISSUE TITLE
Recommended DXGI configuration for Reflex?

### ISSUE THREAD

**Issue by jpark37** [NVIDIAGameWorks/Streamline#24]
For example, Unreal out of the box sets 3 backbuffers and a maximum frame latency of 3. If I want minimum latency, would it help to configure 2 and 1 respectively? How about using the waitable swap chain feature?

**Comment by jake-nv** [comment]
TL;DR Reflex doesn't care because it will attempt to delay frames to be just-in-time (i.e. <1 frame latency).

We generally don't recommend using other "latency reduction approaches" in addition to Reflex, although they shouldn't make Reflex better (or worse).
