### ISSUE TITLE
getSystemCaps() in sl.common leaks D3DKMT adapter handles

### ISSUE THREAD

**Issue by Nukem9** [NVIDIAGameWorks/Streamline#28]
Streamline [calls D3DKMTEnumAdapters2](https://github.com/NVIDIAGameWorks/Streamline/blob/7ac42e47c7dd55b5b6dd6176c0228048636541b2/source/plugins/sl.common/commonInterface.cpp#L148) and doesn't close its output handles.

According to MSDN docs:
> Once the caller of D3DKMTEnumAdapters2 has successfully received an enumeration of the adapters, it is the caller's responsibility to manage the lifespan of the adapter D3DKMT_HANDLEs. These handles are returned through pAdapters, and they must be closed with [D3DKMTCloseAdapter](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/nf-d3dkmthk-d3dkmtcloseadapter).

It's relatively benign. Still a bug nonetheless.

**Comment by jake-nv** [comment]
Thanks for report!

Fix missed upcoming release, but will be in one after.
