### ISSUE TITLE
[NIS] Setting options through slEvaluateFeature doesn't work.

### ISSUE THREAD

**Issue by Bizzarrus** [NVIDIAGameWorks/Streamline#34]
The docs state

> NIS options must be set so that the NIS plugin can track any changes made by the user. This can be done explicitly using the slNISSetOptions or implicitly by adding options as part of the slEvaluateFeature call

However, adding the options as part of the slEvaluateFeature call doesn't seem to work at all - no change in options apply and if slNISSetOptions is never called, the slEvaluateFeature fails with eErrorMissingConstants. 

**Repro:**
Simply pass the desired NIS options through the inputs of the slEvaluateFeature call instead of calling slNISSetOptions, and remove any call to slNISSetOptions, then try to use NIS in the program.

**Comment by jake-nv** [comment]
Thanks for bringing this to our attention.

This is an outdated blurb from previous SL versions.  Currently only certain options (e.g. viewport) can be set via `slEvaluateFeature`.  Please use `slNISSetOptions` to set NIS options.
