### ISSUE TITLE
Missing sl::Result::eWarnOutOfVRAM in sl::getResultAsStr(Result v)

### ISSUE THREAD

**Issue by QDanteQ** [NVIDIAGameWorks/Streamline#38]
https://github.com/NVIDIAGameWorks/Streamline/blob/7b94724d98ee6dccbf06def3ed89f18028647b35/include/sl_helpers.h#L52

**Comment by QDanteQ** [comment]
Also should SL_FAILED(res, sl::Result::eWarnOutOfVRAM) return false, since this is a warning.

**Comment by jake-nv** [comment]
Will get that added. 

“Failed” is perhaps not the best name, but `SL_SUCCEEDED == !SL_FAILED`.  With WarnOutIfVRAM everything is not “ok” we need you to do something.

**Comment by QDanteQ** [comment]
Thank you!
