### ISSUE TITLE
Some packages in external can not be downloaded.

### ISSUE THREAD

**Issue by wsyOverflow** [NVIDIAGameWorks/Streamline#39]
In version 2.4.0, I can only download part of packages by running "setup.bat" and terminate with the following error.
![image](https://github.com/NVIDIAGameWorks/Streamline/assets/41018796/650f0010-0bd3-4936-a79a-5105c44516fd).

The below packages can be downloaded successfully.
![image](https://github.com/NVIDIAGameWorks/Streamline/assets/41018796/3683b136-114e-4359-9a05-0335c9306c42)

**Comment by jake-nv** [comment]
I just tried a fresh clone and setup and packman pulled all the packages without issue. It may have just been a transient issue and you need to try again.

**Comment by jake-nv** [comment]
Any chance you’re in Mainland China (I noticed the 简体字 in your screenshot ☺️)?  If so, could you try through VPN?  I wonder if CloudFlare is blocking your IP from accessing that one URL for some reason….

**Comment by wsyOverflow** [comment]
> Any chance you’re in Mainland China (I noticed the 简体字 in your screenshot ☺️)? If so, could you try through VPN? I wonder if CloudFlare is blocking your IP from accessing that one URL for some reason….

Thank you for your response. Indeed, I am in mainland China, but I have tried using VPN nodes from many regions, and I encounter the same issue when accessing the URL. Additionally, when running "setup.bat" without a VPN, I get connection errors. With a VPN, I encounter a "raise ValueError("check_hostname requires server_hostname")" error.

**Comment by wsyOverflow** [comment]
I attempted to package NRD myself from “https://github.com/NVIDIAGameWorks/RayTracingDenoiser”, using version 4.8.1, and then placed it in the corresponding directory. After a series of operations, I can now successfully package the Streamline SDK and successfully run the Streamline sample.

**Comment by jake-nv** [comment]
That works too. I was going to suggest disabling NRD; unless that’s what you planned to use, in that case you should use the “native” NRD SDK because the SL plugin is going to be deprecated.

**Comment by wsyOverflow** [comment]
Thanks for your response in this issue.

**Comment by jake-nv** [comment]
I’ve contacted the NRD team to try and find out what/if they uploaded that package differently. We need to avoid this in the future.
