### ISSUE TITLE
"FATAL ERROR: Device Removed!" while enabling "Frame Generation"

### ISSUE THREAD

**Issue by wsyOverflow** [NVIDIAGameWorks/Streamline#40]
I try to run frame generation https://github.com/NVIDIAGameWorks/Streamline_Sample, but encountered the following error
![image](https://github.com/NVIDIAGameWorks/Streamline/assets/41018796/f08e74a3-1a9d-434d-a89e-ab0887536599)

Attached log
[log.txt](https://github.com/user-attachments/files/15520982/log.txt)

My computer:
* Win11
* RTX4090
* GeForce Game Ready Driver 555.85

**Comment by wsyOverflow** [comment]
I found a solution to the issue. When packaging the Streamline SDK, there is always a missing dlss_g.dll file. I copied one from bin/x64, which led to the aforementioned problems. Then, I tried copying the one from bin/x64/development, and found that "Frame Generation" could run normally. I hope my findings are helpful to others. However, I'm not sure why this is the case. Is the one in bin/x64 the production version of the DLL?

**Comment by jake-nv** [comment]
Yes, bin/x64/ is “production” binaries. In general all binaries should be from the same configuration. 

When you say dlss_g.dll was missing when packaging, what were you trying to run?  Sounds like something went missing from package.bat…

**Comment by wsyOverflow** [comment]
> Yes, bin/x64/ is “production” binaries. In general all binaries should be from the same configuration.
> 
> When you say dlss_g.dll was missing when packaging, what were you trying to run? Sounds like something went missing from package.bat…
I run "package.bat -develop" after finishing build-all.bat, and there is no sl.dlss_g.dll in _sdk folder.
