### ISSUE TITLE
Exception on slShutdown, when using sl::kFeatureImGUI

### ISSUE THREAD

**Issue by QDanteQ** [NVIDIAGameWorks/Streamline#43]
Hello, I was updating streamline version from 2.2.1 to 2.4.11 and found out the exception on slShutdown. As I see it's caused by sl.imgui. There was no issues on 2.2.1. I also managed to reproduce it in StreamlineSample. It only reproduces when DLSS-G swapchain is created.

Exception occurs here or on previous line. GImGui is null.

https://github.com/NVIDIAGameWorks/Streamline/blob/56e437ccf1789093315a2799989385d6cc7002d9/source/plugins/sl.imgui/imgui_impl_dx12.cpp#L609

**Comment by jake-nv** [comment]
I know there’s been a few changes related to font texture issues in the past few weeks. I’ll have to check if they’re being cherry-picked for the 2.4.x releases.

**Comment by jake-nv** [comment]
Ok, there’s way more imgui fixes than I remembered. Some are Vk-specific, which I don’t believe you’re referring to. Looks like there were 2 in particular that were hard crashes that repro’d in the sample. In any case, most of these should go out in the next release.

**Comment by jake-nv** [comment]
The commit wasn’t written to close this automatically, but it should be in:
https://github.com/NVIDIAGameWorks/Streamline/releases/tag/v2.4.15
