### ISSUE TITLE
Is the DLSS Super Resolution output incorrect when the velocity texture scale is [-1, 1]?

### ISSUE THREAD

**Issue by BobAndBooBoo** [NVIDIAGameWorks/Streamline#47]
Version and Platform:

* streamline v2.4.10
* GPU: RTX4070Ti Super
* Driver: 560.94

When the velocity texture scale passed to `SLWrapper::Get().TagResources_General()` is [-1, 1], it seems that the image becomes blurry during camera movement if `sl::Constants` is set as follows:

```cpp
slConstants.cameraMotionIncluded = sl::Boolean::eTrue;
slConstants.mvecScale = {1.0f, 1.0f };
```

When I pass the velocity texture converted from [-1, 1] to pixel space to `TagResources_General()` and set the following:

```cpp
slConstants.cameraMotionIncluded = sl::Boolean::eTrue;
slConstants.mvecScale = {1.0f / renderSize.x, 1.0f / renderSize.y};
```

it works correctly.

You should be able to verify this in the StreamlineSample using the following steps, but it will crash unless [the issue previously reported](https://github.com/NVIDIAGameWorks/Streamline/issues/44) is resolved...

1. Modify `StreamlineSample.cpp` in StreamlineSample. Set `slConstants.cameraMotionIncluded = sl::Boolean::eFalse` and `slConstants.mvecScale = { 1.0f, 1.0f }`.
2. Modify `mvec.hlsl` in Streamline to convert from pixel space to a scale of [-1, 1].
3. Modify `dlssEntry.cpp` in Streamline so that `mvecPixelSpace = false`.

**Comment by jake-nv** [comment]
DLSS-SR is expecting mvecs in screen space as described in the [DLSS Programming Guide](https://github.com/NVIDIA/DLSS/blob/main/doc/DLSS_Programming_Guide_Release.pdf) section 3.6.1.  If your mvecs are in another format (not supported directly by SL), we recommend doing the conversion in your engine and have SL pass the buffer through untouched (rather than changing SL to support your desired conversion).

**Comment by BobAndBooBoo** [comment]
Upon checking, it seems that the mvecScale settings were incorrect. After setting slConstants.mvecScale = { -1.0f, -1.0f }, the issue no longer occurs when moving the camera, so I will close this issue. Thank you for your confirmation.
