### ISSUE TITLE
Source code for Streamline 1.2.0

### ISSUE THREAD

**Issue by nitrog0d** [NVIDIAGameWorks/Streamline#6]
Pretty much the title, repo is outdated

**Comment by namidairo** [comment]
Repo is in fact two releases behind. 1.3.0 is currently being distributed to partners as of this month.

**Comment by nitrog0d** [comment]
💀

**Comment by duplexsystem** [comment]
@mblacknall why was this closed? the source is still at version 1.1.1 and hasn't seen any new commits since this issue was opened.

**Comment by nitrog0d** [comment]
They even censored the guy lol

**Comment by doodlum** [comment]
I also want confirmation on the state of this project.

**Comment by Akhenaton27** [comment]
> Hemen hemen başlık, repo modası geçmiş

Ayrıca bu projenin durumu hakkında onay istiyorum.

**Comment by Kaldaien** [comment]
Please update the code here. I need to recompile Streamline so that it does not break games by loading the System32 DLL. But games using DLSS3 rely on a private version of Streamline. This whole framework is completely obnoxious and keeping it out-of-date of shipping games is terrible.

**Comment by jake-nv** [comment]
Streamline v1.2 is no longer recommended.  Please move to latest v2.2+.
