### ISSUE TITLE
DLAA?

### ISSUE THREAD

**Issue by duplexsystem** [NVIDIAGameWorks/Streamline#7]
https://developer.nvidia.com/rtx/streamline mentions DLAA being supported but its not in this repo

**Comment by Daasin** [comment]
+2

**Comment by oscarbg** [comment]
Is supported in new Streamline 2.0 release?

**Comment by Snouf-ID** [comment]
+1
I'm really happy to see it noted in there but in fact I can't find it. If you have information on this (soon to be added?)

**Comment by jake-nv** [comment]
It went in with v2.0: 

https://github.com/NVIDIAGameWorks/Streamline/blob/8e7fcb385021b55fb07f1f78237f1bffed5fe601/include/sl_dlss.h#L76
